name: DeepLearning

channels:

- conda-forge

- fastai

- defaults

dependencies:

- fastai

- keras

- scikit-learn

- pandas
- pip:
  - treebeard: 'git+https://github.com/treebeardtech/treebeard.git@health-bar#subdirectory=treebeard-lib'
